// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDk_WBSZSgo2Q0IouLfSoDbZnkcWrpScK0',
    appId: '1:299525860236:web:8c407da30cab60e02f84a9',
    messagingSenderId: '299525860236',
    projectId: 'hamromenu',
    authDomain: 'hamromenu.firebaseapp.com',
    storageBucket: 'hamromenu.appspot.com',
    measurementId: 'G-D8F5S6F3GW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDybRgs-aVMvGiX_bYNgMxk9t4j0NPhP6c',
    appId: '1:299525860236:android:dd73215bd46fdc6a2f84a9',
    messagingSenderId: '299525860236',
    projectId: 'hamromenu',
    storageBucket: 'hamromenu.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDEiLXta6VnM5-4y2UoKr37Ht1T-lgeppc',
    appId: '1:299525860236:ios:2343f74cf44e16372f84a9',
    messagingSenderId: '299525860236',
    projectId: 'hamromenu',
    storageBucket: 'hamromenu.appspot.com',
    iosClientId: '299525860236-drmh8tofafddha4rfcngoo7uj937vv9h.apps.googleusercontent.com',
    iosBundleId: 'com.example.hamroMenuGetx',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDEiLXta6VnM5-4y2UoKr37Ht1T-lgeppc',
    appId: '1:299525860236:ios:2343f74cf44e16372f84a9',
    messagingSenderId: '299525860236',
    projectId: 'hamromenu',
    storageBucket: 'hamromenu.appspot.com',
    iosClientId: '299525860236-drmh8tofafddha4rfcngoo7uj937vv9h.apps.googleusercontent.com',
    iosBundleId: 'com.example.hamroMenuGetx',
  );
}
